export const themes = [
  // { text: "light", name: "light" },
  // { text: "dark", name: "dark" },
  // { text: "cupcake", name: "cupcake" },
  // { text: "bumblebee", name: "bumblebee" },
  // { text: "emerald", name: "emerald" },
  { text: "Light", name: "corporate" },
  // { text: "synthwave", name: "synthwave" },
  // { text: "retro", name: "retro" },
  // { text: "cyberpunk", name: "cyberpunk" },
  // { text: "valentine", name: "valentine" },
  // { text: "halloween", name: "halloween" },
  // { text: "garden", name: "garden" },
  // { text: "forest", name: "forest" },
  // { text: "aqua", name: "aqua" },
  // { text: "lofi", name: "lofi" },
  // { text: "pastel", name: "pastel" },
  // { text: "fantasy", name: "fantasy" },
  // { text: "wireframe", name: "wireframe" },
  // { text: "black", name: "black" },
  // { text: "luxury", name: "luxury" },
  // { text: "dracula", name: "dracula" },
  // { text: "cmyk", name: "cmyk" },
  // { text: "autumn", name: "autumn" },
  { text: "Dark", name: "business" },
  // { text: "acid", name: "acid" },
  // { text: "lemonade", name: "lemonade" },
  // { text: "night", name: "night" },
  // { text: "coffee", name: "coffee" },
  // { text: "winter", name: "winter" },
  // { text: "dim", name: "dim" },
  // { text: "nord", name: "nord" },
  // { text: "sunset", name: "sunset" },
];
